version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - APP_API_TOKEN=${APP_API_TOKEN}
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always
